<article class="container mt-5">

    <header>
        <h1 class="display-4"><?= ($data['post']->getTitle()); ?></h1>
    </header>


    <section>
        <p><?= ($data['post']->getContent()); ?></p>
    </section>


    <footer class="mt-4">
        <p class="text-muted">
            <small>
                Publié par <?= ($data['post']->getAuthor()->getUsername()); ?> le <?= ($data['post']->getCreatedAt()->format('d M Y')); ?>
            </small>
        </p>
    </footer>


</article>

<section class="container mt-5">
    <h2>Commentaires</h2>
    <?php if (!empty($data['comments'])): ?>
        <div class="list-group">
            <?php foreach ($data['comments'] as $comment): ?>
                <div class="list-group-item">

                    <p class="mb-1"><?= ($comment->getContent()); ?></p>

                </div>
            <?php endforeach; ?>
        </div>
    <?php else: ?>
        <p>Aucun commentaire pour cet article.</p>
    <?php endif; ?>
</section>